name: CICD
on:
  [push]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - name: CheckOut code
        uses: actions/checkout@v4
      - name: Validate composer
        run: composer validate --strict  
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test
        run: | 
          chmod +x vendor/bin/phpunit
          composer run-script test
          
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
                cd aibolit_vetclinica/public_html
                git pull origin master