name: CICD
on:
  [push]
jobs:
    Explore-Github-Action:
      runs-on: ubuntu-latest
      steps:
      - name: CheckOut code
        uses: actions/checkout@v4

      - name: Run Test
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run:
          node test_slide.js

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
                cd aibolit_vetclinica/public_html
                git pull origin master