name: CICD
on:
  [push]
jobs:
    Explore-Github-Action:
      runs-on: ubuntu-latest
      steps:
      - name: CheckOut code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
                cd aibolit_vetclinica/public_html
                git pull origin master